# Generated by Django 4.1.7 on 2023-03-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounttype',
            name='annual_interest_rate',
        ),
        migrations.RemoveField(
            model_name='bankaccounttype',
            name='interest_calculation_per_year',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposit_date',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='interest_start_date',
        ),
    ]
