# Generated by Django 4.1.7 on 2023-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bankaccounttype_annual_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='initial_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
